services:
  prometheus:
    image: prom/prometheus:v2.44.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:9.5.3
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
  mssqlexporter:
    image: awaragi/prometheus-mssql-exporter
    ports:
      - 4000:4000
    environment:
      - SERVER=sd-t-promsql01.raet.local
      - USERNAME=Prometheus_Hack
      - PORT=51471
      - PASSWORD=Prometheus_Hack
      - DEBUG=db

volumes:
  prometheus-data:
  grafana-data:
