global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: servicesHTTPS
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets:
          - 'prometheus.demo.do.prometheus.io'
  - job_name: sqlExporters
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'mssqlexporter:4000'
